[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ermai"
version = "3.1.2"
description = "Official ErmAI Python Library and some wrappers for popular SDKs"
authors = [{name = "Gabyface910"}]
requires-python = ">=3.7"
dependencies = [
    "requests",
    "groq",
    "google-genai",
    "openai",
    "anthropic"
]

[tool.setuptools.packages.find]
where = ["src"]
